version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 10
    groups:
      angular:
        patterns:
          - "@angular*"
          - "@ngrx*"
          - "rxjs"
          - "typescript"
          - "zone.js"
          - "tslib"
        exclude-patterns:
          - "@angular-eslint*"
          - "@angular-builders/jest"
        update-types:
          - "minor"
          - "patch"
      codemiror:
        patterns:
          - "codemiror"
          - "@codemiror*"
      ad-grid:
        patterns:
          - "ad-grid*"
      graphql:
        patterns:
          - "@graphql*"
          - "graphql*"
          - "@apollo*"
          - "apollo-angular"
      eslint:
        patterns:
          - "@angular-eslint*"
          - "@typescript-eslint*"
          - "eslint*"
          - "prettier*"
        exclude-patterns:
          - "@angular*"
          - "@ngrx*"
      jest:
        patterns:
          - "jest*"
          - "@angular-builders/jest*"
          - "@types/jest"
      cypress:
        patterns:
          - "cypress"
          - "local-cypress"
      other-dependencies:
        patterns:
          - "*"